/* host_internal.h -- what the host_*.c files share: the types, macros and state
 * used by more than one of them, and a prototype for every function called across
 * files. Included once, by main.c, after its prelude. */
#ifndef NTVDMEX_HOST_INTERNAL_H
#define NTVDMEX_HOST_INTERNAL_H

#include "host_types.h"

static VOID HostProfileDump(VOID);
static VOID WowIcaDeliver(DOS_MACHINE *machine, volatile BYTE *tib, UINT steps);
static UINT32 QpcMicroseconds(LONGLONG ticks);          /* fwd: defined with the lock instruments */
static VOID ModeYTimelineReport(VOID);          /* fwd: north star 1, with the mode-Y remap */
static VOID GusReport(VOID);               /* fwd: north star 2, with the GUS globals */
static INT  ModeYInterpServes(VOID);      /* fwd: north star 1, design C */
static VOID ModeYRingDump(PCSTR why);  /* fwd: north star 1, design C */
static VOID ModeYRingNoteIrq(UINT vector, WORD cs, WORD ip, WORD ss, WORD sp);
static INT HostReadable(PCVOID pointer, SIZE_T length);  /* fwd: defined with the VEH */
static INT InterpreterMemoryPageOk(UINT32 linear);        /* fwd: page-validity guard, defined with V86HostRead8 */
static struct { WORD Cs, Ip, Stub; DWORD Count; } g_SkipIfSite[SKIPIF_SITES];
static struct { WORD Port; DWORD Count; } g_IoHot[IO_HOT_MAX];
static DWORD DpmiSelectorBase(WORD selector);       /* fwd: watchdog resolves the frozen selector base */
/* DPMI PM interrupt-vector table (INT 31h 0204/0205). A client installs its own PM
   handlers here; we store them so a get/set/restore round-trips faithfully. (We still
   service patched INT 21h/31h ourselves -- routing to a client-installed PM handler is
   a deeper item; storing the vectors is what real extenders' save/restore needs.) */
/* `client` distinguishes a vector the CLIENT installed (0205 / INT 21h AH=25h) from
   the host default we pre-load into every entry at mode-switch time. The difference is
   load-bearing in two places: we only ROUTE an interrupt to a handler the client chose,
   and we only INJECT IRQ0 into an INT 08h the client actually hooked -- injecting into
   our own default would be a very confusing way to talk to ourselves. */
static struct { WORD Selector; DWORD Offset; BYTE Client; } g_PmInt[IVT_VECTORS];
static struct { DWORD Base, Size; BYTE Code; } g_DpmiBlock[DPMI_MEMBLK_MAX];
/* DPMI PM EXCEPTION-handler table (INT 31h 0202/0203). Separate from g_PmInt on
   purpose: 0202/0203 address CPU exceptions 00h-1Fh, which are a different namespace
   from the interrupt vectors 0204/0205 addresses -- a client may legitimately install
   a #GP (0Dh) exception handler and an INT 0Dh (IRQ5) interrupt handler at once, and
   collapsing them into one table would make each silently overwrite the other.
   Doom's DOS/4GW makes 45 of these calls -- the biggest single block of UNSUP in the
   session-16 trace -- installing its own fault handlers before it runs the game. */
static struct { WORD Selector; DWORD Offset; INT IsSet; } g_PmException[X86_EXCEPTIONS];
/* DPMI 0303 real-mode callbacks: each slot records the client's PM handler (sel:off)
   and the RMCS buffer (sel:off) to marshal register state through. g_PmReturnSelector is a
   code selector based at DOS_HDLR_SEG (0x500) so the PM handler's IRET lands on the
   planted DPMI_PMRET catcher; allocated lazily on the first 0303. */
static struct { WORD PmSelector; DWORD PmOffset; WORD RmEs; DWORD RmDi; INT IsUsed; } g_Callbacks[DPMI_CB_SLOTS];
static VOID ExecMachineSave(INT depth);    /* fwd: defined with CloseProgramNow */
static BYTE  g_FaultTable[DOS_FLTSITE_N * DPMI_FAULT_TABLE_ENTRY] __attribute__((aligned(16)));
static BYTE  g_FaultStack[DPMI_FAULT_STK_SIZE] __attribute__((aligned(16)));   /* #205 */
static struct _DPMI_DESCRIPTOR { DWORD Base, Limit; BYTE Access, Flags; } g_Ldt[DPMI_LDT_MAX];
static INT AsyncVectorIsOurStub(UINT irq);
static VOID PokeWord(DWORD linear, WORD value);        /* fwd: guest-memory helpers, defined below */
static WORD PeekWord(DWORD linear);
static VOID HostPitSync(VOID);             /* fwd: the guest's clock, driven by both threads */
static VOID HostPitGenerate(VOID);         /* fwd: the crystal half (g_PitCs only)  */
static VOID HostPitDeliver(VOID);          /* fwd: the attempt half (g_Lock, by TRY) */
static INT  V86DeliverDeviceIrq(volatile BYTE *tib);  /* fwd: shared by the main and nested V86 loops */
static INT  DpmiAsyncInjectPm(UINT irq, CONTEXT *context);
static struct { BYTE Irq, Path, State; WORD Cs, Ip; DWORD Flags; } g_IfvTrace[IFV_TRACE_MAX];
static struct { WORD Cs; DWORD Eip, Count; } g_PmInjectSite[PMINJ_SITES];
static VOID MouseChildExited(VOID);          /* fwd: see g_MouseWantRelease */
static VOID InstallReport(PCSTR message, INT isOk);
static HANDLE StdioPebHandle(HANDLE proc, UINT offset);
static VOID HostRecordFinish(VOID);        /* below: patches the header, logs */
static VOID HostMouseButton(INT button, INT down);
/* --- menu + status bar (scaffold; most items are stubs for now) ------------ */
static CHAR g_ProgramName[64] = HOST_PROGRAM_NONE;      /* first part of the status strip    */
static struct { WORD Ax; DWORD Count; }  g_MouseI33Ax[I33_AXN];
static struct { DWORD Linear, Eip, Count; WORD Cs, Ax; BYTE Source; BYTE Context[12]; } g_MouseI33Site[I33_SITEN];
static INT DpmiSelectorIs32(WORD selector);
static VOID VideoTrapSync(VOID);             /* fwd */
static WORD DpmiSegmentToDescriptor(WORD segment);
static INT HostReadable(PCVOID pointer, SIZE_T length);   /* fwd: defined with the
                                                             other memory probes */
static VOID HostFullscreenToggle(HWND window);
static VOID ModifierTrack(BYTE rawScancode, INT extended, INT down);
static struct { DWORD Cs, Ip, Count; BYTE Bytes[10]; } g_RetraceSite[RT_SITES];
static VOID ModeYGr4CloseRun(VOID);       /* defined with the GR4 counters below */
static VOID ModeYRemapSelectBody(PVOID context, INT mask);
static VOID InterpreterMemoryBadNote(UINT32 linear, INT write);   /* defined after v86interp.h (needs icpu) */
static VOID HostPitGenerate(VOID);
static VOID DpmiInstall(INT index);           /* defined just below; used by the helper */
static VOID WowShadowPut(INT index);         /* GH #128: keep the descriptor shadow in step */
static VOID DpmiBreakpointArm(VOID);               /* fwd: a new region may hold a requested BP */
static VOID DpmiBreakpointRearmPending(DWORD currentLinear);   /* fwd: re-plant stepped-over breakpoints */
static INT DpmiServicePmInt(DOS_MACHINE *machine, volatile BYTE *tib, DWORD vector, UINT steps);
static VOID DpmiEnsurePmReturnSelector(VOID);   /* fwd: shared PM-return catcher installer (#2b + 0303) */
static INT V86BiosBop(volatile BYTE *tib, UINT bopNumber, PSTR *logCursor, PSTR base);
/* ── ★★★ THE NESTED RUN: CALL 16-BIT CODE AND WAIT FOR THE ANSWER. (s89, #162) ─────
     Every call into Win16 code so far was ARRANGED from a BOP and taken on the way out
     (wowcall.h): fine for anything the guest asked us to do, impossible for a question
     WINDOWS asks mid-way through its own work -- WM_CTLCOLOR comes from inside a
     control's paint and needs a brush before the paint can go on. This runs the call
     to completion right here: WowCallEnter parks the current context and enters the
     procedure exactly as a deferred callback would (unloaded segments included), and
     this loop drives the guest -- servicing every BOP, USER and GDI calls included,
     the way the PM IRQ injector does -- until the procedure's return stub pops that
     frame (WowCallLeave restores the parked context), then hands the result back.
   ⚠ Only on the guest thread, in protected mode, a Win16 session, below the callback
     depth limit. A run that stops without returning unwinds its frame and says so. */
static INT g_WowWindowNested = 0;
static INT WowCall16SyncEx(DWORD proc, WORD ds, const WORD *args, INT argumentCount,
                              WORD hwnd, WORD message, WORD *result,
                              BYTE *blob, INT blobLength, INT blobArgument,
                              const INT *fix, INT fixupCount);
static struct { HANDLE VddHandle; WORD FirstPort, LastPort; ISV_IO_HANDLERS Handlers; INT IsLive; } g_IsvHooks[ISV_MAX_HOOKS];
/* The interpreter templates' host callbacks, then the templates themselves. */
static inline __attribute__((always_inline)) BYTE V86HostRead8(UINT32 linear);
static inline __attribute__((always_inline)) VOID V86HostWrite8(UINT32 linear, BYTE value);
static inline __attribute__((always_inline)) const volatile BYTE *V86HostCodePointer(UINT32 linear);
static UINT32 V86HostIn(WORD port, INT width);
static VOID V86HostOut(WORD port, INT width, UINT32 byteValue);
static BYTE Pm32HostRead8(UINT32 linear);
static VOID Pm32HostWrite8(UINT32 linear, BYTE value);
static INT Pm32HostCanAccess(UINT32 linear, INT width, INT isWrite);
static UINT32 Pm32HostIn(WORD port, INT width);
static VOID Pm32HostOut(WORD port, INT width, UINT32 value);
#include "v86interp.h"
#include "pm32interp.h"
/* State used from a file other than its owner's (tentative definitions). */
static PFN_ADD_VECTORED_EXCEPTION_HANDLER g_PfnAddVeh;
static PFN_ATTACH_CONSOLE g_PfnAttachConsole;
static PFN_REGISTER_RAW_INPUT_DEVICES g_PfnRegisterRawInput;
static PFN_GET_RAW_INPUT_DATA g_PfnGetRawInput;
static DWORD g_OsVersion;
static DOS_SAFE_SKIPS g_Safe;
static WORD g_DsProbe[DSPROBE_MAX];
static INT g_DsProbeCount;
static WORD g_CsProbe[DSPROBE_MAX];
static INT g_CsProbeCount;
static INT g_Routed;
static INT g_BackToPrompt;
static VDM_COMMAND_INFO g_CommandInfo;
static DOS_MACHINE *g_Machine;
static VDD_BUS g_Bus;
static PIT_STATE g_Pit; static NTVDD_DEVICE g_PitDevice;
static CMOS_STATE g_Cmos; static NTVDD_DEVICE g_CmosDevice;
static PIC_STATE g_Pic; static NTVDD_DEVICE g_PicDevice;
static VIDEO_STATE g_Video; static NTVDD_DEVICE g_VideoDevice;
static INPUT_STATE g_Input; static NTVDD_DEVICE g_InputDevice;
static SPEAKER_STATE g_Speaker; static NTVDD_DEVICE g_SpeakerDevice;
static PCSPEAKER g_PcSpeaker;
static INT g_SpeakerReal;
static OPL_STATE g_Opl; static NTVDD_DEVICE g_OplDevice;
static SB_STATE g_Sb; static NTVDD_DEVICE g_SbDevice;
static GUS_STATE g_Gus; static NTVDD_DEVICE g_GusDevice;
static INT g_GusOn;
static EMU8K_STATE g_Emu8K; static NTVDD_DEVICE g_Emu8KDevice;
static INT g_AweOn;
static INT g_DosVersionForced;
static PCSTR g_DosVersionWhy;
static MPU_STATE g_Mpu; static NTVDD_DEVICE g_MpuDevice;
static COMM_STATE g_Comm; static NTVDD_DEVICE g_CommDevice;
static NETBIOS_STATE g_Net; static NTVDD_DEVICE g_NetDevice;
static BYTE g_GenericStubVector[DOS_GENSTUB_N];
static JOYSTICK_STATE g_Joystick; static NTVDD_DEVICE g_JoystickDevice;
static INT g_JoystickPovMap;
static INT g_WowFoldMute;
static DWORD g_WowFoldDropped;
static AUDIO_STATE g_Audio; static AUDIO_WAVE g_Wave;
static PRESENT_DDRAW g_PresentDdraw;
static DOS_XMS_STATE g_Xms;
static PVOID g_Hma;
static DWORD g_HmaError;
static DWORD g_HmaState, g_HmaProtection;
static DOS_EMS_STATE g_Ems;
static volatile LONG g_Irq0Pending;
static volatile LONG g_IcaPending;
static DWORD g_IcaRaised, g_IcaDelivered, g_IcaNoHandler;
static DWORD g_WowIdleWaits;
static DWORD g_ShimState[WOW_SHIMS], g_ShimError[WOW_SHIMS];
static UINT32 g_PitSyncs;
static UINT32 g_PitAsyncAttempts;
static DWORD g_PitDeliverSkipped;
static LONG g_PmTickOwedMaximum;
static UINT32 g_PmOwedHistogram[9];
static volatile LONG g_PmTickOwed;
static DWORD g_TickGap[12], g_TickGapMaximumMicroseconds, g_TickGapOver;
static volatile LONG g_Irq1Pending;
static INT g_PmIrq0Latch;
static INT g_InPmIrq;
static CRITICAL_SECTION g_Lock;
static LARGE_INTEGER g_QpcFrequency;
static INT g_LockSite, g_LockHoldSite, g_LockWaitSite;
static UINT32 g_LockHoldMicroseconds, g_LockWaitMicroseconds, g_UiGapMicroseconds;
static INT g_UiTickMinimumMs;
static DWORD g_UiTickSkips;
static DWORD g_UiHookPresents, g_UiTimerPresents;
static DWORD g_KeyMessageHistogram[8];
static DWORD g_KeyMessageMaximumMs, g_KeyMessageCount;
static DWORD g_KeyDeliveryHistogram[8];
static DWORD g_KeyDeliveryMaximumMs, g_KeyDeliveryCount;
static DWORD g_Irq1Checks, g_Irq1NoIf, g_Irq1In08, g_Irq1In09;
static DWORD g_Irq1AsyncInjected;
static INT g_KeyIrqRetry;
static DWORD g_Irq1AsyncRetry;
static CRITICAL_SECTION g_PitCs;
static HWND g_Window;
static HANDLE g_KeyEvent;
static volatile LONG g_Running;
static INT g_DpmiPm;
static INT g_PmClientExited;
static DWORD g_DpmiCodeBase;
static DWORD g_PatchMapLinear[DPMI_PMAP_SLOTS];
static BYTE g_PatchMapVector[DPMI_PMAP_SLOTS];
static DWORD g_PatchMapCount;
static INT g_PmNoIrq;
static INT g_PmVehPass;
static volatile LONG g_PmEntryEip;
static UINT g_DpmiCpMaximum;
static DWORD g_WowPmBase[WOW_PMBASE_MAX];
static DWORD g_PmWatchOffset;
static UINT g_PmWatchSegment;
static DWORD g_BreakpointDump[DPMI_BP_MAX];
static DWORD g_BreakpointSkip[DPMI_BP_MAX];
static DWORD g_BreakpointMode[DPMI_BP_MAX];
static BYTE g_BreakpointPending[DPMI_BP_MAX];
static DWORD g_BreakpointReport[DPMI_BP_MAX];
static BYTE g_BreakpointDone[DPMI_BP_MAX];
static INT g_BreakpointCount;
static volatile LONG g_DpmiIteration;
static volatile LONG g_DpmiDone;
static volatile LONG g_DpmiWatchdogGeneration;
static INT g_Headless;
static DWORD g_EventIo;
static DWORD g_IoExtra;
static DWORD g_Irq0Injected;
static DWORD g_Irq0TimeLast[IRQ0TL_SECS];
static DWORD g_Irq0GapHistogram[8];
static DWORD g_Irq0GapMaximumMs, g_Irq0GapCount;
static LONGLONG g_Irq0Start, g_Irq0TimePrevious;
static DWORD g_Irq0IoPrevious, g_Irq0WorstGapMs, g_Irq0WorstGapIo;
static DWORD g_Irq0WorstCs, g_Irq0WorstIp;
static DWORD g_Irq0NoteCs, g_Irq0NoteIp;
static DWORD g_Irq0RaiseCount, g_Irq0AttemptsCount, g_Irq0NieCount, g_Irq0YieldCount;
static DWORD g_Irq0AnomalyCount, g_Irq0AnomalyMicroseconds, g_Irq0AnomalyIo;
static DWORD g_Irq0AnomalyRaise, g_Irq0AnomalyAttempts, g_Irq0AnomalyNie, g_Irq0AnomalyYield;
static DWORD g_Irq0AnomalyGeneration, g_Irq0AnomalyDelete;
static DWORD g_Irq0NormalCount, g_Irq0NormalMicroseconds, g_Irq0NormalIo;
static DWORD g_Irq0WorstRaise, g_Irq0WorstAttempts, g_Irq0WorstNie, g_Irq0WorstYield;
static DWORD g_Irq0WorstPerMicroseconds;
static DWORD g_Irq0Skip;
static DWORD g_Irq0SkipIf;
static DWORD g_Irq0SkipStub;
static DWORD g_HeartbeatDs;
static DWORD g_EventIntPending;
static DWORD g_EventIoString;
static DWORD g_Irq1Injected;
static DWORD g_PmIrqReflects;
static DWORD g_IrqNInjected;
static DWORD g_IrqNRefuseTotal;
static volatile LONG g_WoundDown;
static WORD g_IoLastPort;
static DWORD g_EventHistogram[EV_HIST_MAX];
static DWORD g_V86MicrosecondsTotal, g_HostMicrosecondsEvent[EV_HIST_MAX];
static DWORD g_BopHistogram[BYTE_VALUES];
static DWORD g_PitPaceCalls;
static DWORD g_XsStart, g_XsSeconds, g_XsSnapshot[XS_SECS][XS_N];
static INT g_IoHotCount;
static WORD g_Unclaimed[IO_UNCLAIMED_MAX];
static INT g_UnclaimedCount;
static UINT g_CaptureMs;
static DWORD g_CaptureDelayMs, g_CaptureStart;
static INT g_Capture;
static INT g_NoA000;
static INT g_NoPmPatch;
static DWORD g_NoPmPatchMinimum;
static DWORD g_MemoryDumpLinear, g_MemoryDumpLength;
static INT g_P12Offset;
static DWORD g_OplTraceCount;
static DWORD g_OplTraceDrop;
static INT g_OplTraceOn;
static INT g_ModeYInterpOffset;
static INT g_ModeYInterp;
static DWORD g_ModeYSlices, g_ModeYInstructions, g_ModeYBails, g_ModeYBailMp;
static INT g_ModeYRingOn;
static INT g_ModeYPmOffset;
static INT g_ModeYPmDetect;
static DWORD g_HeadlessMs;
static volatile DWORD g_DpmiEnterCs;
static volatile DWORD g_DpmiEnterEip;
static volatile DWORD g_DpmiLastEvent;
static volatile DWORD g_DpmiLastCs;
static volatile DWORD g_DpmiLastEip;
static volatile DWORD g_DpmiLastVector;
static INT g_DpmiBlockCount;
static DWORD g_DpmiOwned[DPMI_OWNED_MAX];
static INT g_DpmiOwnedCount;
static WORD g_DpmiDosBlock[DPMI_DOSBLK_MAX];
static INT g_DpmiDosBlockCount;
static INT g_LdtClientMark;
static INT g_PmExitCode;
static DWORD g_LeCodeSize[DPMI_LE_MAX];
static INT g_LeCodeCount;
static DWORD g_PmVector8ArmedMs;
static INT g_PmAppHookedTimer;
static WORD g_PmAppTimerSelector;
static DWORD g_PmAppTimerOffset;
static WORD g_PmDefaultSelector;
static INT g_DpmiVi;
static BYTE g_BiosUnimplemented[BYTE_VALUES];
static INT g_ExecDepth;
static volatile LONG g_CloseRequest;
static INT g_TopIsShell;
static CHAR g_ProgramName[PROGRAM_NAME_SIZE];
static WORD g_PmReturnSelector;
static WORD g_DpmiFaultSelector;
static WORD g_DpmiFaultCodeSelector;
static INT g_LdtNext;
static WORD g_LdtFree[DPMI_LDT_MAX];
static INT g_LdtFreeCount;
static volatile BYTE *g_TibDebug;
static HANDLE g_ComSpool[COMM_MAX_PORTS];
static INT g_ComFailed[COMM_MAX_PORTS];
static INT g_BdaReady;
static WORD g_Int15StubOffset;
static DWORD g_PrintScreenJobs, g_PrintScreenErrors;
static BYTE g_PrintScreenStatus;
static volatile LONG g_IrqNPending[PIC_LINES];
static const BYTE g_IrqOrder[14];
static DWORD g_IrqNRetryTry, g_IrqNRetryOk, g_IrqNRetryWhy;
static DWORD g_IrqRaised[PIC_LINES];
static DWORD g_IrqRaisedAny;
static HANDLE g_HostCpu;
static DWORD g_QiBits;
static INT g_QiSuspended;
static INT g_QiKeysAsync;
static volatile LONG g_InExec;
static volatile LONG g_AsyncContextWrite;
static volatile LONG g_PauseWant;
static INT g_BehaveDos622;
static DWORD g_PauseCount, g_PauseCooperative, g_PauseMs;
static HANDLE g_CourierEvent;
static DWORD g_AsyncInjected;
static DWORD g_AsyncBail;
static DWORD g_QiCalls;
static volatile LONG g_QiStatus;
static DWORD g_AsyncNestBlocked;
static DWORD g_Irq0IsrSince;
static DWORD g_Irq0IsrBlocks;
static DWORD g_Irq0IsrTimeouts;
static DWORD g_Irq0IsrStrict;
static DWORD g_Irq0IsrAuto;
static INT g_Irq0AutoEoi;
static DWORD g_Irq0ResyncDrop;
static LONG g_AsyncWhy;
static DWORD g_AsyncWhyHistogram[PIC_LINES_PER_CHIP][ASYNC_WHY_MAX];
static DWORD g_IfvCensus[IFV_PATHS][8];
static DWORD g_IfvShadow[PIC_LINES];
static DWORD g_IfvStarveT0, g_IfvStarveMaximumMs, g_IfvStarveCount;
static INT g_IfvStarveOpen;
static LONG g_IfvTraceCount;
static DWORD g_IfvReenter[PIC_LINES];
static volatile LONG g_AsyncPmActive;
static DWORD g_AsyncPmEip, g_AsyncPmEsp, g_AsyncPmEflags;
static WORD g_AsyncPmCs, g_AsyncPmSs;
static DWORD g_AsyncPmInjected;
static DWORD g_AsyncInjectedLine[PIC_LINES];
static DWORD g_PmWatch[DPMI_WATCH_MAX];
static INT g_PmWatchCount;
static BYTE g_PmWatchRel[DPMI_WATCH_MAX];
static DWORD g_LeLoadBase;
static DWORD g_PmCooperativeLine[PIC_LINES_PER_CHIP];
static DWORD g_PmInjectDecl[2], g_PmInjectDeclTl[IRQ0TL_SECS];
static UINT32 g_DmaPollInAsync, g_DmaPollMainline;
static DWORD g_AsyncEarlyBailLogged;
static INT g_AsyncSiteCount;
static INT g_AsyncSiteFull;
static volatile LONG g_SimIntBusy;
static volatile LONG g_NestedRm;
static PCSTR g_FloppyImage;
static HANDLE g_Stdio;
static PCSTR g_StdioHow;
static PCSTR g_StdioSource;
static DWORD g_StdioParentProcessId;
static DWORD g_DmxSamples, g_DmxBusy[12], g_DmxMixerOk;
static DWORD g_DmxOverdue, g_DmxOverdueMaximum, g_DmxAnyBusy;
static INT g_PitPaceOn, g_PitPaceMs;
static INT g_PitPacePriority;
static INT g_PitPaceInject;
static volatile LONGLONG g_Int15WaitEnd;
static volatile LONGLONG g_Int15EventEnd;
static volatile DWORD g_Int15EventLinear;
static DWORD g_Int15Waits, g_Int15Events, g_Int15Posted, g_Int15Busy;
static INT g_PmTopDispatch;
static INT g_PmDispatchTop;
static INT g_CourierOn;
static DWORD g_CourierWakes, g_CourierInjected, g_CourierTries, g_CourierGiveUp;
static INT g_CpuSpeedIndex;
static UINT g_CpuSpeedReferenceMhz;
static volatile LONG g_CpuSpeedDuty;
static volatile LONG g_CpuSpeedDutyRm;
static DWORD g_CpuSpeedRunMs, g_CpuSpeedHeldMs;
static DWORD g_CpuSpeedMissed;
static DWORD g_CpuSpeedHoldMaximumMicroseconds;
static DWORD g_CpuSpeedDebtMaximumMicroseconds;
static DWORD g_CpuSpeedRanMicroseconds;
static DWORD g_CpuSpeedWallMicroseconds;
static UINT g_CpuSpeedGranularityMs;
static DWORD g_CpuSpeedRoundTripMicroseconds;
static DWORD g_CpuSpeedPeriodMs;
static DWORD g_CpuSpeedPeriods;
static DWORD g_StartMs;
static HANDLE g_CpuSpeedRelease;
static DWORD g_CpuSpeedCooperativeCatches, g_CpuSpeedCooperativeTimeouts;
static INT g_CpuAffinityOn;
static DWORD g_CpuAffinityGuest, g_CpuAffinityRest, g_CpuAffinityCpuCount;
static MPU_STATE g_GusMidi;
static UINT32 g_TypematicDelayMicroseconds;
static UINT32 g_TypematicPeriodMicroseconds;
static DWORD g_TypematicSpiDelay, g_TypematicSpiSpeed;
static UINT32 g_TypematicSent, g_TypematicOsRepeats;
static volatile LONG g_MouseX, g_MouseY, g_MouseButtons;
static volatile LONG g_MouseDx, g_MouseDy;
static INT g_MouseRawOk;
static INT g_MouseSensitivity;
static DWORD g_MouseWmInput, g_MouseRawAbsolute, g_MouseI33[16], g_MouseI33Other;
static DWORD g_MouseI33AxOverflow, g_MouseI33SiteCount, g_MouseI33SiteOverflow;
static DWORD g_SimIntUnhandled, g_SimIntVector[IVT_VECTORS];
static INT g_SimIntReflect;
static INT g_MouseAbsent;
static INT g_TextDump;
static volatile LONG g_MouseHidden;
static volatile LONG g_MousePressCount[MS_BTNS], g_MouseReleaseCount[MS_BTNS];
static DWORD g_MouseEdges;
static volatile LONG g_MouseEventMask, g_MouseEventSegment, g_MouseEventOffset;
static DWORD g_MouseEventInstalls;
static volatile LONG g_MouseEventPend;
static INT g_MouseCallbackActive;
static DWORD g_MouseCallbackInjected, g_MouseCallbackDone, g_MouseCallbackLost, g_MouseCallbackPm, g_MouseCallbackStray;
static INT g_MouseCallbackTrace;
static DWORD g_MouseCallbackWhy[MOUSE_CB_WHY_COUNT];
static DWORD g_MouseEventRaised;
static INT g_HostCursorMode;
static volatile LONG g_Captured;
static volatile LONG g_MouseWantCapture;
static volatile LONG g_MouseAutoCaptureDone;
static volatile LONG g_MouseWantRelease;
static volatile LONG g_MouseSeamless;
static DWORD g_MouseShapeSets;
static volatile LONG g_MouseGraphicsCursorDefined;
static DWORD g_MouseGraphicsCursorBadPointer;
static DWORD g_MouseAccelerationCalls;
static DWORD g_MouseAltCalls;
static volatile LONG g_MouseTextCursorAnd, g_MouseTextCursorXor;
static DWORD g_MouseStateBadPointer;
static DWORD g_MouseI33Unimplemented;
static NE_MODULE g_WowModule[WOW_MAX_MOD];
static BYTE *g_WowImage[WOW_MAX_MOD];
static CHAR g_WowName[WOW_MAX_MOD][16];
static INT g_WowModuleCount;
static WORD g_WowEntryCx;
static WORD g_WowPspSegment;
static WORD g_PmTransferSegment;
static WORD g_WowPathSegment;
static WORD g_WowEnvironmentSegment;
static DWORD g_WowCallbackLinear;
static WORD g_WowPspSelector[WOW_PSP_TRACK];
static DWORD g_WowPspLinear[WOW_PSP_TRACK];
static WORD g_WowPspEnvironment[WOW_PSP_TRACK];
static INT g_WowPspCount;
static WORD g_PmTransferParagraphs;
static INT g_WowLaunch;
static HHOOK g_LowLevelKeyboard;
static INT g_LowLevelKeyboardOn;
static HANDLE g_ExecThread;
static INT g_ExecPriorityForeground;
static LONG g_JoystickThreadStarted;
static NTVDMEX_SETTINGS g_Settings;
static NTVDMEX_SETTINGS g_SettingsDisk;
static PCSTR g_ShellOverride;
static DOS_MACHINE *g_DosMachine;
static INT g_FrameSkip;
static DOS_SB_CONFIG g_SbConfig;
static INT g_DspVersionForced;
static INT g_XmsOn, g_EmsOn;
static UINT g_ConventionalKbWant;
static WORD g_DosMemoryTop;
static DWORD g_WindowSizeLive;
static DWORD g_AspectLive;
static const INT g_SettingsPages[NTVDMEX_PAGE_COUNT];
static UINT32 g_PitCatchupClamped;
static UINT32 g_PitGapMaximum;
static DWORD g_VbeWaits;
static volatile DWORD g_RetracePending, g_RetraceCs, g_RetraceIp, g_RetraceAl, g_RetraceCx, g_RetraceIdles;
static DWORD g_DmaPollEip[DMAPOLL_MAX], g_DmaPollHits[DMAPOLL_MAX];
static UINT g_DmaPollCount, g_DmaPollOverflow;
static DWORD g_PollStack[POLLSTK_MAX], g_PollStackHits[POLLSTK_MAX];
static DWORD g_PollGap[10], g_PollGapMaximumMicroseconds;
static UINT g_PollStackCount, g_PollStackOverflow;
static PVOID g_ModeYView[MODEY_NSEC];
static INT g_ModeYRemap;
static DWORD g_ModeYSwaps, g_ModeYFanouts, g_ModeYFail;
static DWORD g_ModeYSelectorCalls;
static DWORD g_ModeYSelectorSame;
static DWORD g_ModeYSelectorZero;
static DWORD g_ModeYTimelineT0;
static DWORD g_ModeYTimelineIns[YTL_SECS];
static UINT64 g_ModeYTimelineInterpreterCycles[YTL_SECS];
static DWORD g_ModeYFanoutBarWrites[2];
static DWORD g_ModeYFanoutBarDistinct[2];
static DWORD g_ModeYFanoutBar4Way[2];
static DWORD g_ModeYSampleCrossSame[2], g_ModeYSampleCrossDiff[2], g_ModeYSampleWrites[2];
static DWORD g_ModeYSampleCrossEqualBytes[2], g_ModeYSampleCrossTotalBytes[2];
static DWORD g_ModeYSampleP1Equal[2][4], g_ModeYSampleP1Total[2][4];
static DWORD g_ModeYSampleDeliveredEqual[2], g_ModeYSampleDeliveredTotal[2];
static DWORD g_ModeYLatchOk, g_ModeYLatchUnsolved, g_ModeYLatchDescriptor;
static DWORD g_ModeYGr4Calls, g_ModeYGr4Mismatch, g_ModeYGr4Pair[4][6];
static DWORD g_ModeYGr4SinceSelector, g_ModeYGr4Runs[10], g_ModeYGr4RunPlanes[VIDEO_PLANES];
static DWORD g_ModeYGr4Moves;
static INT g_A000Protection;
static INT g_P12Interp;
static DWORD g_InterpreterMemoryBadReads, g_InterpreterMemoryBadWrites, g_InterpreterMemoryBadLogged;
static const V86_CPU *g_InterpreterCpu;
static DWORD g_GuestThreadId;
static WORD g_WowLastId;
static WORD g_WowLastFrom;
static INT g_HostPoolSpill;
static WORD g_DpmiHandlerSelector;
static INT g_WowSchedOn;
static WORD g_WowDgroupSelector;
static WOWSCHED_SLOT g_WowSchedSlots[WOWSCHED_MAX];
static INT g_WowWindowNested;
static DWORD g_WowSchedSwitches;
static WORD g_WowSchedLaunchChild, g_WowSchedShell;
static INT g_WowCallOn;
static BYTE g_PmDispatch[IVT_VECTORS];
static DWORD g_PmDispatchCount[IVT_VECTORS][BYTE_VALUES];
static DWORD g_Wow32Serviced, g_Wow32Unimplemented, g_Wow32Declined;
static BYTE *g_WowShadow;
static DWORD g_WowSyncWrites;
static DWORD g_PmIrqRmReflects, g_PmIrqRmFail;
/* Functions called from a file other than their own. */
static VOID OsCompatBind(VOID);
static BOOL OsCompatAttachConsole(DWORD processId);
static VOID DsProbeLoad(VOID);
static PCSTR NtvdmexRoot(VOID);
static PCSTR NtvdmexPath(PCSTR subdirectory, PCSTR name);
static UINT LauncherCompilerVariables(PCSTR environment, DWORD environmentCapacity, PSTR out, DWORD outCapacity);
static VOID GusReport(VOID);
static INT StrStrNoCase(PCSTR block, PCSTR name);
static BYTE NetSubmit(PVOID context, NETBIOS_REQUEST *request);
static VOID HmaTry(VOID);
static VOID Irq0Latch(VOID);
static INT PmTickTake(VOID);
static VOID TickDeliveredNote(VOID);
static VOID KeyLatencyPop(VOID);
static UINT32 QpcMicroseconds(LONGLONG ticks);
static UINT64 QpcMicroseconds64(LONGLONG ticks);
static VOID HostLockEnter(INT site);
static VOID HostLockLeave(VOID);
static INT HostLockTry(INT site);
static BYTE PatchMapGet(DWORD linear);
static VOID PatchMapSet(DWORD linear, BYTE vector);
static VOID PatchMapClear(DWORD linear);
static VOID Irq0DeliveredNote(VOID);
static VOID SkipIfSiteNote(DWORD codeSegment, DWORD instructionPointer, DWORD stub);
static PSTR ExecBegin(DOS_MACHINE *machine, volatile BYTE *tib, PSTR cursor);
static VOID CriticalSnapshot(volatile BYTE *tib);
static VOID CriticalRaise(DOS_MACHINE *machine, volatile BYTE *tib, PSTR *logCursor);
static INT CriticalReturn(DOS_MACHINE *machine, volatile BYTE *tib, PSTR *logCursor);
static INT PmRwHardwareFail(DOS_MACHINE *machine, volatile BYTE *tib, BYTE function, DWORD win32Error, PSTR *logCursor);
static VOID ComTransmitSink(PVOID context, INT port, BYTE byteValue);
static WORD BiosEquipmentWord(VOID);
static VOID BiosBdaRefreshEquipment(VOID);
static VOID SerialInitialize(VOID);
static VOID SerialOut(PCSTR buffer, PCSTR end);
static VOID VddLoadThirdParty(VOID);
static VOID WowLogFlush(PSTR base, PSTR *logCursor);
static INT LptSpoolPut(BYTE character);
static VOID LptTransmitSink(PVOID context, INT port, BYTE byteValue);
static INT DosPrnOut(PVOID context, BYTE character);
static INT KeyboardActionEntry(INT keyboardAction);
static INT Int15Hooked(VOID);
static VOID DosAuxOut(PVOID context, BYTE character);
static INT MemoryReadable(ULONG_PTR address, SIZE_T length);
static UINT IrqPmVector(UINT irq);
static VOID HostPitResyncCheck(VOID);
static INT Irq0CanDeliver(VOID);
static VOID Irq0Ack(VOID);
static INT Irq0PmClaim(VOID);
static VOID Irq0PmUnclaim(VOID);
static VOID IfvNote(INT path, DWORD flags);
static DWORD PmWatchAddress(INT index);
static VOID PmInjectDeclineNote(INT why, WORD cs, DWORD eip);
static INT AsyncInjectIrq(UINT irq);
static INT AsyncVectorIsOurStub(UINT irq);
static VOID HostIrqSink(PVOID context, BYTE irq);
static VOID PokeWord(DWORD linear, WORD value);
static VOID PokeDword(DWORD linear, DWORD value);
static WORD PeekWord(DWORD linear);
static INT IfOrVif(DWORD flags);
static INT IsOurStubCsIp(DWORD cs, DWORD ip);
static DWORD PeekWidth(DWORD linear, INT width);
static VOID PokeWidth(DWORD linear, DWORD value, INT width);
static VOID VdmStateSample(PCSTR label, volatile BYTE *tib, INT *budget);
static VOID InjectInt(volatile BYTE *tib, UINT vector);
static INT DosTerminate(DOS_MACHINE *machine, PVOID tib, PSTR *logCursor, PSTR base);
static UINT RecoveryRead(VOID);
static VOID RecoveryWrite(UINT value);
static VOID RecoveryOk(VOID);
static INT MruLoad(CHAR out[MRU_MAX][MAX_PATH]);
static VOID MruAdd(PCSTR path);
static INT InstallPerform(INT want, INT force, PSTR message, DWORD cap);
static INSTALL_STATE InstallStatusText(PSTR message, DWORD cap);
static INT InstallVerb(PCSTR command);
static INT CommandLineHasForce(PCSTR command);
static INT CommandLineBare(PCSTR command);
static INT LaunchShellVdm(VOID);
static VOID InstallReport(PCSTR message, INT isOk);
static VOID RecoveryUninstall(PSTR *logCursor);
static INT HostHasFloppy(VOID);
static INT HostHasCdrom(VOID);
static PDOS_DISK_GEOMETRY DiskFor(UINT drive);
static INT DiskIo(UINT drive, UINT32 lba, UINT count, BYTE *guest, INT write);
static VOID StdioFlush(VOID);
static HANDLE StdioPebHandle(HANDLE proc, UINT offset);
static PCSTR StdioInitialize(VOID);
static PCSTR StdioInitializeVdm(VOID);
static VOID HostConsoleOut(PVOID context, BYTE ch);
static INT HostConsoleIn(PVOID context);
static UINT64 HostTimeMicroseconds(VOID);
static VOID OplTraceWrite(BYTE registerIndex, BYTE value);
static VOID OplTraceDump(VOID);
static VOID OplPumpTime(VOID);
static LONGLONG Int15QpcAfterMicroseconds(DWORD microseconds);
static VOID PitPacerTimerStart(HMODULE winmmModule);
static DWORD WINAPI PitPacerThread(LPVOID param);
static DWORD WINAPI TickCourierThread(LPVOID parameter);
static UINT HostCpuMhz(VOID);
static VOID ExecEnterMark(VOID);
static VOID ExecLeaveMark(VOID);
static VOID CpuSpeedCooperativePark(VOID);
static VOID CpuSpeedTimelineDump(PCSTR tag);
static VOID CpuSpeedRecompute(VOID);
static DWORD WINAPI CpuSpeedThread(LPVOID param);
static VOID HostAudioFill(PVOID context, INT16 *out, UINT32 frames);
static VOID HostMidiSink(PVOID context, UINT32 message);
static VOID HostMidiSysEx(PVOID context, const BYTE *message, UINT32 length);
static VOID GusMidiToSynth(PVOID context, BYTE byteValue);
static VOID PlanesDumpBeside(PCSTR bitmapPath);
static VOID HostKeyScancode(BYTE rawScancode, INT extended, INT isBreak);
static VOID HostKeyTypematicInitialize(VOID);
static LONGLONG QpcTicks(UINT32 microseconds);
static VOID HostKeyPresent(VOID);
static VOID HostKeyTypematic(VOID);
static DWORD WINAPI SynthKeyThread(LPVOID parameter);
static DWORD WINAPI QueueIrqProbeThread(LPVOID parameter);
static DWORD WINAPI HeartbeatThread(LPVOID parameter);
static VOID HostRecordFinish(VOID);
static VOID AsyncWhyReport(VOID);
static VOID ExecShareReport(VOID);
static VOID IfvReport(VOID);
static DWORD WINAPI HeadlessDeadlineThread(LPVOID parameter);
static INT TypeInPush(PCSTR text);
static INT HostConsoleInNoBlock(PVOID context);
static INT HostConsolePeek(PVOID context);
static VOID HostSetFlags(volatile BYTE *tib, BYTE carryFlag, BYTE zeroFlag);
static PVOID XmsHostAllocate(PVOID context, DWORD kilobytes);
static VOID XmsHostFree(PVOID context, PVOID memory, DWORD kilobytes);
static VOID HostXms(volatile BYTE *tib);
static PVOID EmsHostAllocate(PVOID context, DWORD pages);
static VOID EmsHostFree(PVOID context, PVOID memory, DWORD pages);
static VOID HostEms(volatile BYTE *tib);
static UINT I33Width(VOID);
static UINT I33Height(VOID);
static INT I33XShift(VOID);
static LONG I33VirtualX(LONG pixelX);
static INT I33Text(VOID);
static LONG I33VirtualY(LONG pixelY);
static LONG I33VirtualMaximumY(VOID);
static VOID MouseEventRaise(LONG bits);
static VOID MouseButtonEdges(LONG prev, LONG now);
static VOID HostMouseButton(INT button, INT down);
static VOID MouseChildExited(VOID);
static INT CaptureAllowed(VOID);
static INT MouseGoesToGuest(VOID);
static LONG I33ClampX(LONG virtualX);
static LONG I33ClampY(LONG virtualY);
static VOID I33ResetState(VOID);
static UINT Int15MoveBlockAt(volatile BYTE *tib, DWORD gdtLinear);
static VOID ExecMachineSave(INT depth);
static VOID ExecMachineRestore(INT depth, PSTR *logCursor);
static INT CloseProgramNow(DOS_MACHINE *machine, PVOID tib, PSTR *logCursor, PSTR base);
static VOID MouseInt33(volatile BYTE *tib, INT source);
static INT MouseAnyHandler(VOID);
static INT MouseEventQueueTake(MOUSE_EVENT_ENTRY *event, LONG *outAx, WORD *segment, DWORD *offset);
static VOID MouseCallbackTry(volatile BYTE *tib);
static VOID MouseCallbackReturn(volatile BYTE *tib);
static VOID MouseDrawGraphicsCursor(BYTE *pixels, INT width, INT height, INT stride);
static PCSTR CommandLineAfterArgv0(PCSTR cursor);
static INT LaunchIsWow(PCSTR command);
static INT WowModuleOfSelector(WORD selector);
static INT WowUserAnchor(WORD thunkId, WORD argumentBytes, WORD returnStub);
static INT WowShellAnchor(WORD thunkId, WORD argumentBytes, WORD returnStub);
static INT WowCommonDialogAnchor(WORD thunkId, WORD argumentBytes, WORD returnStub);
static INT WowKeyboardAnchor(WORD thunkId, WORD argumentBytes, WORD returnStub);
static INT WowSoundAnchor(WORD thunkId, WORD argumentBytes, WORD returnStub);
static INT WowGdiAnchor(WORD thunkId, WORD argumentBytes, WORD returnStub);
static INT WowKernel2Stub(WORD thunkId, WORD returnStub);
static WORD WowHostAllocate(WORD paras);
static PSTR WowPspEnvironmentCheck(PSTR cursor, PCSTR where);
static VOID WowProbeLoad(PCSTR command);
static INT WowRefuse(PCSTR command);
static VOID HostPresentHook(PVOID context);
static VOID TrayRemove(HWND window);
static INT StringsEqual(PCSTR first, PCSTR second);
static LRESULT CALLBACK LowLevelKeyboardProcedure(INT code, WPARAM wParam, LPARAM lParam);
static VOID InputCaptureSet(HWND window, INT isOn);
static INT OtherHostsRunning(VOID);
static VOID BackgroundPriorityTick(HWND window);
static VOID HostPanicRelease(VOID);
static DWORD WINAPI CaptureWatchdogThread(LPVOID parameter);
static VOID HostFullscreenToggle(HWND window);
static UINT64 JoystickNowMicroseconds(PVOID context);
static VOID JoystickPollEnsure(VOID);
static VOID SettingsNoteOverride(INT settingId, PCSTR source, DWORD value);
static VOID SettingsLogSources(VOID);
static VOID SettingsApply(HWND window, const NTVDMEX_SETTINGS *settings, INT live);
static VOID SettingsApplyPresent(PRESENT_DDRAW *present, const NTVDMEX_SETTINGS *settings);
static VOID SettingsApplyDevices(const NTVDMEX_SETTINGS *settings);
static UINT32 SettingsOutputHz(const NTVDMEX_SETTINGS *settings);
static VOID MenuViewSync(HWND window);
static VOID HostApplyWindowSize(HWND window, DWORD index);
static VOID SettingsApplyLive(HWND window);
static INT_PTR CALLBACK SettingsPageProcedure(HWND dialog, UINT message, WPARAM wParam, LPARAM lParam);
static INT_PTR CALLBACK SettingsDialogProcedure(HWND dialog, UINT message, WPARAM wParam, LPARAM lParam);
static VOID KeyMessageNote(VOID);
static VOID KeyPushMake(LPARAM lParam);
static VOID KeyPushBreak(LPARAM lParam);
static VOID ModifierTrack(BYTE rawScancode, INT extended, INT down);
static VOID HostReleaseModifiers(VOID);
static DWORD WINAPI UiThread(LPVOID argument);
static VOID RegistersLoad(NTVDD_REGISTERS *registers, volatile BYTE *tib);
static VOID RegistersStore(NTVDD_REGISTERS *registers, volatile BYTE *tib);
static VOID IoHotNote(WORD port, DWORD cs, DWORD ip);
static VOID HostRtcNow(PVOID context, PIT_RTC_READING *out);
static INT HostRtcSet(PVOID context, const PIT_RTC_READING *reading, INT what);
static INT HostTickTake(UINT32 *ticks, UINT32 *wraps, UINT32 *since);
static VOID HostTicksSet(PVOID context, UINT32 ticks);
static VOID HostSetTicks(PVOID context, UINT32 ticks);
static VOID HostPitGuard(PVOID context, INT enter);
static VOID HostPitGenerate(VOID);
static VOID HostPitDeliver(VOID);
static VOID HostPitSync(VOID);
static VOID PitLatchNote(BYTE command);
static VOID Int10WaitAfter(VOID);
static VOID RetraceNote(volatile BYTE *tib, WORD port, INT isIn, DWORD cs, DWORD ipAfter);
static VOID RetraceIdle(VOID);
static INT HostTryIo(volatile BYTE *tib, VDD_BUS *bus);
static INT HostTryIoRetro(volatile BYTE *tib, VDD_BUS *bus);
static INT HostTryIoString(volatile BYTE *tib, VDD_BUS *bus);
static INT DpmiSelectorIs32(WORD selector);
static INT HostTryIoPm(volatile BYTE *tib, VDD_BUS *bus);
static UINT64 ModeYTimelineRdtsc(VOID);
static VOID ModeYRemapFlushReport(VOID);
static INT ModeYRemapInitialize(VOID);
static VOID ModeYRemapSelect(PVOID context, INT mask);
static VOID ModeYBailNote(DWORD cs, DWORD ip, const volatile BYTE *bytes);
static VOID ModeYTimelineReport(VOID);
static VOID ModeYRemapSelectBody(PVOID context, INT mask);
static BYTE *ModeYRemapPlane(PVOID context, INT plane);
static VOID ModeYGr4CloseRun(VOID);
static VOID ModeYRemapReadMap(PVOID context, INT plane);
static VOID ModeYRemapWriteMode(PVOID context, INT writeMode);
static VOID VideoTrapSync(VOID);
static INT ModeYInterpServes(VOID);
static INT ModeYNeedsInterp(VOID);
static INT InterpreterMemoryPageOk(UINT32 linear);
static INT ModeYPmNeedsInterp(VOID);
static VOID ModeYPmRun(volatile BYTE *tib);
static VOID InterpreterMemoryBadNote(UINT32 linear, INT write);
static UINT32 HostGuestPc(VOID);
static VOID ModeYRingDump(PCSTR why);
static VOID ModeYRingNoteIrq(UINT vector, WORD cs, WORD ip, WORD ss, WORD sp);
static VOID HostProfileStart(VOID);
static VOID HostProfileDump(VOID);
static INT32 HostInterpPaced(volatile BYTE *tib, INT32 cap);
static INT HostReadable(PCVOID pointer, SIZE_T length);
static INT HostWritable(PVOID pointer, SIZE_T length);
static LONG CALLBACK DpmiCrashVeh(EXCEPTION_POINTERS *pointers);
static LONG WINAPI HostUnhandledFilter(EXCEPTION_POINTERS *pointers);
static DWORD WINAPI DpmiWatchdog(LPVOID param);
static INT DpmiHostIndex(VOID);
static WORD DpmiHandlerCodeSelector(VOID);
static WORD DpmiSegmentToDescriptor(WORD segment);
static WORD WowCallbackSelector(VOID);
static VOID DpmiSegmentToDescriptorForget(WORD selector);
static VOID WowProbeLdtMatrix(PCSTR tag);
static INT WowPlaceV86(DOS_MACHINE *machine, WORD *entryCs, WORD *eip, WORD *entryDs, WORD *entrySs, WORD *esp);
static VOID WowProbeSelectors(VOID);
static VOID DpmiInstallDefaultPmHandlers(DOS_MACHINE *machine);
static VOID DpmiInstall(INT index);
static VOID DpmiInstallFaultTrampoline(VOID);
static VOID DpmiArmFaultTrampoline(volatile BYTE *tib, WORD flag);
static DWORD DpmiSelectorBase(WORD selector);
static DWORD DpmiRecoverFlatEip(DWORD lo16, BYTE vector, INT *candidateCount);
static INT DpmiSelectorDescriptor(WORD selector, UINT32 *accessRights, UINT32 *limit);
static DWORD DpmiBopVector(DWORD csValue, DWORD eip);
static DWORD DpmiPmEip(volatile BYTE *tib);
static VOID DpmiPatchCodeRegion(DWORD base, DWORD limit, INT is32BitRegion);
static VOID DpmiLeLearn(const BYTE *buffer, DWORD length);
static VOID DpmiScanCodeBlocks(VOID);
static VOID DpmiBreakpointLoad(VOID);
static VOID DpmiBreakpointResolveCodeBase(DWORD base);
static VOID DpmiBreakpointResolveSegment(UINT segmentNumber, DWORD base);
static VOID DpmiBreakpointArm(VOID);
static VOID DpmiBreakpointRearmPending(DWORD currentLinear);
static INT DpmiBreakpointDisarm(DWORD linear);
static VOID DpmiUnpatch(VOID);
static VOID DpmiRepatch(VOID);
static DWORD Wow32ReturnOverride(WORD thunkId);
static INT Wow32ModeOverride(WORD thunkId);
static VOID Wow32ModeLoad(VOID);
static VOID Wow32ReturnLoad(VOID);
static INT WowSchedFree(VOID);
static INT WowSchedPick(WORD current);
static INT WowSchedRunnable(WORD current, INT depth);
static INT WowSchedTopLevel(const WOWSCHED_SLOT *slot);
static WORD WowSchedCurrentTask(VOID);
static VOID WowTaskDirectoryHere(WORD task);
static VOID WowTaskChdir(WORD task, PSTR *logCursor);
static VOID WowSchedSetCurrent(WORD task);
static INT WowSchedRetarget(WORD hwnd, WORD *stackSegment, WORD *stackPointer, DWORD *stackSegmentBase, WORD *prev);
static VOID WowSchedUntarget(WORD prev);
static INT WowSchedInterTaskLive(VOID);
static VOID WowQuietLoad(VOID);
static VOID WowSchedLoad(VOID);
static VOID WowCallLoad(VOID);
static VOID DpmiInvokeCallback(DOS_MACHINE *machine, volatile BYTE *tib, INT slot);
static INT DpmiDispatchToPmHandler(DOS_MACHINE *machine, volatile BYTE *tib, DWORD vector, UINT steps);
static DWORD DpmiCallerOffset(volatile BYTE *tib, DWORD offset);
static DWORD DpmiRmcsPointer(volatile BYTE *tib, DWORD esBase);
static VOID RmcsToTib(volatile BYTE *tib, const RMCS_REGS *registers);
static VOID TibToRmcs(volatile BYTE *tib, RMCS_REGS *registers, WORD flags);
static VOID DpmiRmcsProbe(volatile BYTE *tib, DWORD esBase, UINT slot, DWORD interruptNumber);
static DWORD Wow32HostSelectorToLinear(WORD selector, PVOID context);
static INT DpmiOwnedFind(DWORD handle);
static VOID DpmiLdtRelease(INT index);
static INT DpmiLdtTake(VOID);
static INT DpmiClientSelectorOk(WORD selector);
static VOID WowShadowPut(INT index);
static INT WowShadowSync(PSTR *logCursor);
static INT WowVendorApiEntry(DOS_MACHINE *machine, WORD *selector, WORD *offset);
static PSTR PmInt21Transfer(DOS_MACHINE *machine, volatile BYTE *tib, DWORD ah, PSTR cursor);
static PSTR PmInt21Lfn(DOS_MACHINE *machine, volatile BYTE *tib, PSTR cursor);
static INT DpmiReflectIrqToRm(DOS_MACHINE *machine, volatile BYTE *tib, UINT vector);
static INT DpmiServicePmIntBody(DOS_MACHINE *machine, volatile BYTE *tib, DWORD vector, UINT steps);
static INT DpmiServicePmInt(DOS_MACHINE *machine, volatile BYTE *tib, DWORD vector, UINT steps);
static VOID DpmiEnsurePmReturnSelector(VOID);
static INT DpmiAsyncInjectPm(UINT irq, CONTEXT *context);
static INT WowCall16Sync(DWORD proc, WORD ds, const WORD *args, INT argumentCount, WORD hwnd, WORD message, WORD *result);
static DWORD ShimGlobal16(INT operation, DWORD firstArgument, DWORD secondArgument);
static PVOID ShimMapFlat(WORD segment, DWORD offset, INT isProtectedMode);
static VOID IsvIoIn(PVOID self, WORD port, BYTE width, UINT32 *value);
static VOID IsvIoOut(PVOID self, WORD port, BYTE width, UINT32 value);
static VOID WowShimsLoad(VOID);
static VOID IsvBop(volatile BYTE *tib, DWORD subfunction, PSTR *logCursor);
static INT DpmiNestedFault(volatile BYTE *tib, DWORD event, DWORD eip);
static INT WowCall16SyncEx(DWORD proc, WORD ds, const WORD *args, INT argumentCount, WORD hwnd, WORD message, WORD *result, BYTE *blob, INT blobLength, INT blobArgument, const INT *fix, INT fixupCount);
static LRESULT WowControlColour(HWND window, WORD window16, UINT message, WPARAM wParam, LPARAM lParam, INT *handled);
static LRESULT WowOwnerDraw(HWND window, WORD window16, UINT message, WPARAM wParam, LPARAM lParam, INT *handled);
static INT WowSend16Blob(WORD window16, WORD message, WORD wParam, BYTE *blob, INT blobLength, const INT *fix, INT fixupCount, WORD *result);
static INT WowSend16Now(WORD window16, WORD message, WORD wParam, DWORD lParam, WORD *result);
static INT DpmiInjectPmIrq(DOS_MACHINE *machine, volatile BYTE *tib, UINT interruptVector, UINT steps);
static VOID WowIcaDeliver(DOS_MACHINE *machine, volatile BYTE *tib, UINT steps);
static INT DpmiInjectPmMouseCallback(DOS_MACHINE *machine, volatile BYTE *tib, UINT steps);
static VOID DpmiClientTeardown(VOID);
static INT DpmiRunPmInterp(DOS_MACHINE *machine, volatile BYTE *tib);
static VOID DosWowPublish(volatile BYTE *handlerArea, volatile BYTE *controlTable, UINT currentDrive);
static INT V86DeliverDeviceIrq(volatile BYTE *tib);
static INT V86BiosBop(volatile BYTE *tib, UINT bopNumber, PSTR *logCursor, PSTR base);

#endif
