#!/usr/bin/env python3
"""gen-vbepm.py -- assemble src/vdd/vbe_pm.asm and write src/vdd/vbe_pm.h (#53).

The VBE 2.0 protected-mode interface block is real 32-bit x86 code that a client copies
and calls; it is kept as assembly SOURCE and turned into a C byte array here, so the
bytes in the host are always the bytes of the file a reader can review. Run after any
edit to vbe_pm.asm:

    python3 tools/gen-vbepm.py
"""
import os, struct, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "vdd", "vbe_pm.asm")
OUT = os.path.join(ROOT, "src", "vdd", "vbe_pm.h")

with tempfile.TemporaryDirectory() as td:
    binp = os.path.join(td, "vbe_pm.bin")
    subprocess.check_call(["nasm", "-f", "bin", SRC, "-o", binp])
    blob = open(binp, "rb").read()

win, start, pal, ports = struct.unpack_from("<4H", blob, 0)
lines = []
for i in range(0, len(blob), 12):
    lines.append("    " + ", ".join("0x%02X" % b for b in blob[i:i + 12]) + ",")
hdr = """/* vbe_pm.h -- GENERATED by tools/gen-vbepm.py from src/vdd/vbe_pm.asm. Do not edit by hand.
 *
 * The VBE 2.0 protected-mode interface block handed out by INT 10h AX=4F0Ah (#53):
 * a 4-word table (SetWindow, SetDisplayStart, SetPalette, port list -- each an offset
 * from the start of the block), the I/O port list, and relocatable 32-bit code.
 */
#ifndef VBE_PM_H
#define VBE_PM_H
#define VBE_PM_LEN       %du
#define VBE_PM_SETWINDOW 0x%04Xu
#define VBE_PM_SETSTART  0x%04Xu
#define VBE_PM_SETPAL    0x%04Xu
#define VBE_PM_PORTS     0x%04Xu
static const unsigned char vbe_pm_block[VBE_PM_LEN] = {
%s
};
#endif
""" % (len(blob), win, start, pal, ports, "\n".join(lines))
open(OUT, "w").write(hdr)
print("wrote %s: %d bytes, setwindow=%#x setstart=%#x setpal=%#x ports=%#x"
      % (os.path.relpath(OUT, ROOT), len(blob), win, start, pal, ports))
