#!/usr/bin/env python3
"""gen-vgafont.py -- emit src/vdd/vga_font_8x16.h, an 8x16 text-mode font.

Renders all 256 CP437 code points from a monospace TTF into 8x16 1bpp cells
(bit 7 = leftmost pixel of each row) and packs them into a C array. CP437 is the
classic DOS code page, so box-drawing + the ASCII range come out right via the
'cp437' codec. A placeholder until the authentic IBM VGA ROM font is dropped in;
good enough to prove the text renderer.

Usage:  python3 tools/gen-vgafont.py [--preview]
"""
import sys
from PIL import Image, ImageFont, ImageDraw

FONT_PATH = "/System/Library/Fonts/Supplemental/Andale Mono.ttf"
PT = 16              # render size; tuned so glyphs fill the 8x16 cell
Y_OFF = -2          # vertical nudge to seat glyphs in the cell
CELL_W, CELL_H = 8, 16

def render_glyph(font, ch):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, Y_OFF), ch, fill=255, font=font)
    rows = []
    px = img.load()
    for y in range(CELL_H):
        b = 0
        for x in range(CELL_W):
            if px[x, y] > 110:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows

def build():
    font = ImageFont.truetype(FONT_PATH, PT)
    glyphs = []
    for i in range(256):
        try:
            ch = bytes([i]).decode("cp437")
        except Exception:
            ch = " "
        if i in (0, 0x20, 0xFF):     # NUL / space / nbsp -> blank cell
            ch = " "
        glyphs.append(render_glyph(font, ch))
    return glyphs

def emit_header(glyphs, path):
    out = []
    out.append("/* vga_font_8x16.h -- GENERATED by tools/gen-vgafont.py. Do not edit by hand.")
    out.append(" * 8x16 text-mode font, 256 glyphs, 16 bytes each (bit 7 = leftmost pixel). */")
    out.append("#ifndef NTVDMEX_VGA_FONT_8X16_H")
    out.append("#define NTVDMEX_VGA_FONT_8X16_H")
    out.append("#include <stdint.h>")
    out.append("static const uint8_t vga_font_8x16[256][16] = {")
    for i, rows in enumerate(glyphs):
        body = ",".join("0x%02x" % b for b in rows)
        out.append("    {%s}, /* 0x%02x */" % (body, i))
    out.append("};")
    out.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, "(%d glyphs)" % len(glyphs))

def preview(glyphs, text, path):
    scale = 4
    img = Image.new("L", (len(text) * CELL_W * scale, CELL_H * scale), 30)
    px = img.load()
    for ci, ch in enumerate(text):
        rows = glyphs[ord(ch) & 0xFF]
        for y in range(CELL_H):
            for x in range(CELL_W):
                if rows[y] & (1 << (7 - x)):
                    for sy in range(scale):
                        for sx in range(scale):
                            px[(ci*CELL_W+x)*scale+sx, y*scale+sy] = 255
    img.save(path)
    print("wrote preview", path)

if __name__ == "__main__":
    g = build()
    emit_header(g, "src/vdd/vga_font_8x16.h")
    if "--preview" in sys.argv:
        preview(g, "C:\\> dir /w  Hello, World! 0123", "vm/font_preview.png")
