#!/usr/bin/env python3
"""gen-vgafont.py -- emit src/vdd/vga_font_8x16.h from the IBM VGA 8x16 ROM font.

Source: tools/IBM_VGA_8x16.bin -- the authentic IBM VGA character ROM font
(256 glyphs x 16 bytes, bit 7 = leftmost pixel; CP437 ordering), the de-facto
DOS text-mode "system font". Dumped from the IBM VGA BIOS ROM (spacerace/romfont,
public domain); raw character bitmaps are not copyrightable as such, so they ship
freely here. The .bin layout already matches what the renderer wants, so this just
wraps it in a C array.

Usage:  python3 tools/gen-vgafont.py [--preview]
"""
import sys

# One entry per ROM table we ship. The 8x8 is NOT optional and must NOT be derived from
# the 8x16: DOS programs ask for it by name (INT 10h AX=1130h BH=3/4) and render their own
# text from the pointer we hand back, so a downsampled stand-in becomes THEIR garbled text.
# Skyroads asks for exactly BH=3 and BH=4.
FONTS = [
    (8,  "tools/IBM_VGA_8x8.bin",  "src/vdd/vga_font_8x8.h",  "vga_font_8x8"),
    (14, "tools/IBM_VGA_8x14.bin", "src/vdd/vga_font_8x14.h", "vga_font_8x14"),
    (16, "tools/IBM_VGA_8x16.bin", "src/vdd/vga_font_8x16.h", "vga_font_8x16"),
]
BIN_PATH = "tools/IBM_VGA_8x16.bin"
OUT_PATH = "src/vdd/vga_font_8x16.h"

def emit_header(data, path, h=16, name="vga_font_8x16"):
    assert len(data) == 256 * h, "expected %d bytes, got %d" % (256 * h, len(data))
    guard = "NTVDMEX_%s_H" % name.upper()
    base = path.split("/")[-1]
    out = ["/* %s -- GENERATED by tools/gen-vgafont.py. Do not edit by hand." % base,
           " * The IBM VGA 8x%d ROM font (CP437): 256 glyphs, %d bytes each, bit 7 =" % (h, h),
           " * leftmost pixel. Source: tools/IBM_VGA_8x%d.bin (public-domain ROM dump). */" % h,
           "#ifndef " + guard,
           "#define " + guard,
           "#include <stdint.h>",
           "static const uint8_t %s[256][%d] = {" % (name, h)]
    for i in range(256):
        row = data[i*h:i*h+h]
        out.append("    {%s}, /* 0x%02x */" % (",".join("0x%02x" % b for b in row), i))
    out.append("};")
    out.append("#endif")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote", path, "(256 glyphs, %d rows)" % h)

def preview(data, text, path):
    from PIL import Image
    scale = 4
    img = Image.new("L", (len(text)*8*scale, 16*scale), 30); px = img.load()
    for ci, ch in enumerate(text):
        g = data[(ord(ch) & 0xFF)*16:(ord(ch) & 0xFF)*16+16]
        for y in range(16):
            for x in range(8):
                if g[y] & (0x80 >> x):
                    for sy in range(scale):
                        for sx in range(scale):
                            px[(ci*8+x)*scale+sx, y*scale+sy] = 255
    img.save(path); print("wrote preview", path)

if __name__ == "__main__":
    for h, binp, outp, name in FONTS:
        emit_header(open(binp, "rb").read(), outp, h, name)
    data = open(BIN_PATH, "rb").read()
    if "--preview" in sys.argv:
        preview(data, "C:\\> dir /w  Hello, World! 0123", "vm/font_preview.png")
