#!/usr/bin/env python3
"""gen-vgafont.py -- emit src/vdd/vga_font_8x16.h from the IBM VGA 8x16 ROM font.

Source: tools/IBM_VGA_8x16.bin -- the authentic IBM VGA character ROM font
(256 glyphs x 16 bytes, bit 7 = leftmost pixel; CP437 ordering), the de-facto
DOS text-mode "system font". Dumped from the IBM VGA BIOS ROM (spacerace/romfont,
public domain); raw character bitmaps are not copyrightable as such, so they ship
freely here. The .bin layout already matches what the renderer wants, so this just
wraps it in a C array.

Usage:  python3 tools/gen-vgafont.py [--preview]
"""
import sys

BIN_PATH = "tools/IBM_VGA_8x16.bin"
OUT_PATH = "src/vdd/vga_font_8x16.h"

def emit_header(data, path):
    assert len(data) == 256 * 16, "expected 4096 bytes, got %d" % len(data)
    out = ["/* vga_font_8x16.h -- GENERATED by tools/gen-vgafont.py. Do not edit by hand.",
           " * The IBM VGA 8x16 ROM font (CP437): 256 glyphs, 16 bytes each, bit 7 =",
           " * leftmost pixel. Source: tools/IBM_VGA_8x16.bin (public-domain ROM dump). */",
           "#ifndef NTVDMEX_VGA_FONT_8X16_H",
           "#define NTVDMEX_VGA_FONT_8X16_H",
           "#include <stdint.h>",
           "static const uint8_t vga_font_8x16[256][16] = {"]
    for i in range(256):
        row = data[i*16:i*16+16]
        out.append("    {%s}, /* 0x%02x */" % (",".join("0x%02x" % b for b in row), i))
    out.append("};")
    out.append("#endif")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote", path, "(256 glyphs from", BIN_PATH + ")")

def preview(data, text, path):
    from PIL import Image
    scale = 4
    img = Image.new("L", (len(text)*8*scale, 16*scale), 30); px = img.load()
    for ci, ch in enumerate(text):
        g = data[(ord(ch) & 0xFF)*16:(ord(ch) & 0xFF)*16+16]
        for y in range(16):
            for x in range(8):
                if g[y] & (0x80 >> x):
                    for sy in range(scale):
                        for sx in range(scale):
                            px[(ci*8+x)*scale+sx, y*scale+sy] = 255
    img.save(path); print("wrote preview", path)

if __name__ == "__main__":
    data = open(BIN_PATH, "rb").read()
    emit_header(data, OUT_PATH)
    if "--preview" in sys.argv:
        preview(data, "C:\\> dir /w  Hello, World! 0123", "vm/font_preview.png")
