#!/usr/bin/env python3
"""gen-opl-tables.py -- generate src/vdd/opl_tables.h for the OPL2 FM core.

The host links -nostdlib, so there is no libm to call at runtime and these tables
cannot be computed on the fly. They are generated here from their mathematical
definitions (the same log/exp identities the YM3812 implements in silicon), which
keeps them ours and keeps the header reproducible: re-run this script and diff.

The OPL works in the LOG domain, and so do we -- that is the whole trick that makes
FM cheap. Amplitudes multiply, so in the log domain they ADD: an operator's output
is `exp2(-(logsin[phase] + envelope + total_level + key_scale))`, i.e. one table
lookup, some integer adds, and a shift. No multiplies, no floats at runtime.

Units: one log unit = 1/256 of a factor-of-two in amplitude (about 0.0235 dB), so
  - the envelope's 0.1875 dB step is 8 log units
  - the total-level register's 0.75 dB step is 32 log units

    ./tools/gen-opl-tables.py > src/vdd/opl_tables.h
"""
import math

def logsin_table():
    """-log2(sin(x)) for the first quarter period, in log units.

    Only a quarter wave is stored; the synth mirrors and negates it to build the
    full sine, exactly as the hardware does. Sample at the middle of each step
    (i + 0.5) so the table is symmetric about the quarter boundary and never has
    to evaluate sin(0), which is infinite."""
    out = []
    for i in range(256):
        s = math.sin((i + 0.5) * math.pi / 512.0)
        out.append(int(round(-math.log2(s) * 256.0)))
    return out

def exp_table():
    """2^(-i/256), scaled by 4096.

    Indexed by the low 8 bits of a total attenuation; the high bits become a right
    shift. Values run 4096 down to 2048, so one table covers every octave."""
    return [int(round(math.pow(2.0, -i / 256.0) * 4096.0)) for i in range(256)]

def emit(name, ctype, values, per_line):
    print("static const %s %s[%d] = {" % (ctype, name, len(values)))
    for i in range(0, len(values), per_line):
        row = ", ".join("%5d" % v for v in values[i:i + per_line])
        print("    %s," % row)
    print("};")
    print()

def main():
    ls, ex = logsin_table(), exp_table()
    print("/* opl_tables.h -- GENERATED by tools/gen-opl-tables.py. Do not edit.")
    print(" *")
    print(" * Log-domain tables for the OPL2 FM core (see vdd_opl_synth.c). One log")
    print(" * unit = 1/256 of a factor-of-two in amplitude; the envelope's 0.1875 dB")
    print(" * step is 8 units and the total-level step is 32. */")
    print("#ifndef NTVDMEX_OPL_TABLES_H")
    print("#define NTVDMEX_OPL_TABLES_H")
    print()
    print("#include <stdint.h>")
    print()
    print("/* -log2(sin(x)) * 256, quarter wave (the synth mirrors it). */")
    emit("opl_logsin", "uint16_t", ls, 8)
    print("/* 2^(-i/256) * 4096: the fractional part of an attenuation. */")
    emit("opl_exp", "uint16_t", ex, 8)
    print("/* Largest logsin entry, so callers can size their headroom. */")
    print("#define OPL_LOGSIN_MAX %d" % max(ls))
    print()
    print("#endif /* NTVDMEX_OPL_TABLES_H */")

if __name__ == "__main__":
    main()
