#!/usr/bin/env python3
"""Generate the host's mouse-cursor table from a real .cur/.ico file.

The INT 33h driver cursor used to be hand-drawn ASCII art in main.c, and it showed:
"the mouse cursor is not quite the right shape" was the one cosmetic defect the demo
sweep turned up. This decodes an actual cursor so the shape is the artwork's, not a
programmer's recollection of it.

    python3 tools/mkcursor.py cursors/cursor-pointer.cur

Emits the C table on stdout. Format matches what overlay_cursor() already consumes --
'o' = outline (palette index 0), 'X' = fill (index 15), ' ' = transparent -- so only
the DATA changes, not the drawing code.

Only 1/4/8-bpp DIB cursors are handled, which is what a 16x16 arrow is. A cursor using
colours beyond black and white is rejected rather than silently approximated: our
overlay writes palette INDICES into the guest's framebuffer, and the guest owns that
palette (BUBBLES reprograms all 16 entries), so there is no third colour we could
honestly pick.
"""
import struct
import sys


def decode(path):
    d = open(path, 'rb').read()
    reserved, kind, count = struct.unpack_from('<HHH', d, 0)
    if reserved or kind not in (1, 2) or count < 1:
        raise SystemExit("%s: not an .ico/.cur" % path)
    # Directory entry 0. In a .cur the planes/bitcount fields hold the hotspot.
    w, h, ncol, _res = struct.unpack_from('<BBBB', d, 6)
    hot_x, hot_y = struct.unpack_from('<HH', d, 10)
    off = struct.unpack_from('<I', d, 18)[0]
    hdr, dw, dh, planes, bpp = struct.unpack_from('<iiihh', d, off)
    if bpp not in (1, 4, 8):
        raise SystemExit("%s: %d-bpp not handled" % (path, bpp))
    W, H = dw, dh // 2                      # DIB height covers XOR **and** AND masks
    pal_n = ncol if ncol else (1 << bpp)
    pal_off = off + hdr
    pal = [struct.unpack_from('<BBBB', d, pal_off + i * 4) for i in range(pal_n)]

    def stride(bits):                        # DIB rows pad to a 4-byte boundary
        return ((W * bits + 31) // 32) * 4

    xor_off = pal_off + pal_n * 4
    and_off = xor_off + stride(bpp) * H
    rows = []
    for y in range(H):
        src = H - 1 - y                      # bottom-up
        xr = d[xor_off + src * stride(bpp):]
        am = d[and_off + src * stride(1):]
        row = ''
        for x in range(W):
            if bpp == 8:   idx = xr[x]
            elif bpp == 4: idx = (xr[x // 2] >> 4) if x % 2 == 0 else (xr[x // 2] & 0xF)
            else:          idx = (xr[x // 8] >> (7 - x % 8)) & 1
            if (am[x // 8] >> (7 - x % 8)) & 1:
                row += ' '                   # AND=1, XOR=0 -> transparent
                continue
            b, g, r, _ = pal[idx]
            if r < 0x40 and g < 0x40 and b < 0x40:   row += 'o'
            elif r > 0xC0 and g > 0xC0 and b > 0xC0: row += 'X'
            else:
                raise SystemExit("%s: pixel (%d,%d) is #%02X%02X%02X -- only black and "
                                 "white can be mapped to guest palette indices" % (path, x, y, r, g, b))
        rows.append(row.rstrip())
    return rows, W, H, hot_x, hot_y


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    rows, W, H, hx, hy = decode(sys.argv[1])
    print("/* Generated by tools/mkcursor.py from %s -- %dx%d, hotspot (%d,%d)." % (
        sys.argv[1], W, H, hx, hy))
    print("   Do not hand-edit: regenerate from the artwork instead. */")
    print("static const char *const MS_CURSOR[%d] = {" % H)
    for r in rows:
        print('    "%s",' % r.replace('\\', '\\\\').replace('"', '\\"'))
    print("};")


if __name__ == '__main__':
    main()
