#!/usr/bin/env python3
"""needles.py -- cut byte needles out of an NE's segment images, for vdmdump.

The question this serves: *where does a correct loader put krnl386's segments?*
We can answer it by searching a live stock ntvdm.exe for bytes that can only have
come from a segment image -- but only if we pick bytes the loader does not
rewrite. A relocated site differs between the file and memory, so a needle that
straddles one never matches.

So: walk the segment's relocation records, expand every CHAINED record's chain
(each site holds the offset of the next -- terminated by 0xffff), mark every
patched byte, and cut needles only from runs that no fixup touches. Byte
diversity is required too: a 32-byte run of 0x00 matches half of memory and
proves nothing.

    python3 tools/ne/needles.py guest/ne/krnl386.exe > needles.txt

Output is vdmdump's needle file: one "<name> <hex>" per line.
"""
import sys
from nedump import NE

NEEDLE_LEN = 32
PER_SEG = 4
MIN_DISTINCT = 12           # distinct byte values required inside a needle


# Bytes each NE source type rewrites. 0=LOBYTE 2=SEGMENT 3=FAR_ADDR(16:16)
# 5=OFFSET 11=48-bit pointer(16:32) 13=32-bit offset. Unknown -> assume 4, which
# only ever costs us a candidate needle.
SRC_SIZE = {0: 1, 2: 2, 3: 4, 5: 2, 11: 6, 13: 4}


def patched_bytes(ne, seg):
    """Offsets within the segment image that the loader rewrites."""
    img = ne.d[seg["file_off"]:seg["file_off"] + seg["length"]]
    hit = set()
    for r in ne.relocs(seg):
        size = SRC_SIZE.get(r["addr_type"] & 0x7f, 4)
        off = r["offset"]
        if r["rel_type"] & 0x04:                            # ADDITIVE: one site
            for k in range(size):
                hit.add(off + k)
            continue
        # CHAINED: the site holds the offset of the next site, 0xffff ends it.
        seen = 0
        while off != 0xFFFF and off + 1 < len(img) and seen < 20000:
            for k in range(size):
                hit.add(off + k)
            nxt = img[off] | (img[off + 1] << 8)
            if nxt == off:
                break
            off = nxt
            seen += 1
    return img, hit


def cut(img, hit, seg_index, want=PER_SEG):
    """Pick `want` needles spread across the image, avoiding every patched byte."""
    n = len(img)
    clean = []
    i = 0
    while i + NEEDLE_LEN <= n:
        if any((i + k) in hit for k in range(NEEDLE_LEN)):
            i += 1
            continue
        chunk = img[i:i + NEEDLE_LEN]
        # Reject filler: a run dominated by one value (padding, zero fill) will
        # match all over memory and prove nothing about where the segment went.
        common = max(chunk.count(b) for b in set(chunk))
        if len(set(chunk)) >= MIN_DISTINCT and common * 3 <= NEEDLE_LEN:
            clean.append((i, chunk))
            i += NEEDLE_LEN
        else:
            i += 1
    if not clean:
        return []
    # Spread the picks over the segment rather than taking the first few: a
    # partially-loaded segment should still produce a hit.
    out = []
    for j in range(want):
        k = (j * (len(clean) - 1)) // max(1, want - 1) if want > 1 else 0
        off, chunk = clean[k]
        name = "seg%d@0x%04x" % (seg_index, off)
        if not any(o == off for o, _ in out):
            out.append((off, (name, chunk)))
    return [v for _, v in out]


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    ne = NE(sys.argv[1])
    print("# needles from %s -- generated by tools/ne/needles.py" % sys.argv[1])
    for seg in ne.segments():
        img, hit = patched_bytes(ne, seg)
        got = cut(img, hit, seg["i"])
        print("# segment %d: file 0x%06x len %d, %d relocation records, "
              "%d patched bytes, %d needles"
              % (seg["i"], seg["file_off"], seg["length"],
                 len(ne.relocs(seg)), len(hit), len(got)))
        for name, chunk in got:
            print("%s %s" % (name, chunk.hex()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
